# Generated by Django 4.1.2 on 2022-10-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auth_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='auth',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
