# Generated by Django 4.1.2 on 2022-10-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auth_birthday_auth_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='categoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinterest', to='Admin.category'),
        ),
    ]
