# Generated by Django 4.1.2 on 2023-07-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_remove_auth_category_alter_auth_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
