# Generated by Django 4.1.2 on 2023-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_auth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='Otp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whitelisttoken',
            name='token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='whitelisttoken',
            name='useragent',
            field=models.TextField(),
        ),
    ]
