# Generated by Django 4.1.2 on 2023-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_auth_otp_alter_auth_email_alter_auth_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelisttoken',
            name='token',
            field=models.TextField(),
        ),
    ]
