# Generated by Django 4.1.2 on 2023-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_whitelisttoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.TextField(max_length=255),
        ),
    ]
