# Generated by Django 4.1.2 on 2023-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_alter_auth_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
