# Generated by Django 4.1.2 on 2022-10-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsapplication',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
