# Generated by Django 4.1.2 on 2022-10-22 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_auth_otpstatus'),
        ('recruiter', '0002_jobsapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplicants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(default='')),
                ('cv', models.FileField(default='Auth/dummy.jpg', upload_to='jobapplicant/')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to='Admin.auth')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobsapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
