# Generated by Django 4.1.2 on 2022-10-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_auth_otpstatus'),
        ('recruiter', '0005_userread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.auth'),
        ),
        migrations.AlterField(
            model_name='userread',
            name='webnotify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_read', to='recruiter.webnotification'),
        ),
    ]
