# Generated by Django 4.1.2 on 2022-10-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_auth_otpstatus'),
        ('recruiter', '0007_alter_jobsapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='Admin.auth'),
        ),
    ]
