# Generated by Django 4.1.2 on 2022-10-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_alter_userread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userread',
            name='user',
        ),
    ]
